dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: /home/vadim/Documents/personal/huggingface/training_dynamics/structural-probes/example/data/en_ewt-ud-sample/
    train_path: en_ewt-ud-train.conllu
    dev_path: en_ewt-ud-dev.conllu
    test_path: en_ewt-ud-test.conllu
  embeddings:
    type: subword #{token,subword}
    root: /home/vadim/Documents/personal/huggingface/training_dynamics
    train_path: lol_train.pkl
    dev_path: lol_dev.pkl
    test_path: lol_test.pkl
  batch_size: 20
model:
  tokenizer: bert-base-cased
  hidden_dim: 768 # ELMo hidden dim
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: BERT-disk # BERT-disk, BERT-disk, 
  use_disk: True
  model_layer: 0 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_signature: word # word, word_pair
  task_name: parse-depth
  maximum_rank: 768
  psd_parameters: True
  diagonal: False
  params_path: predictor.params
probe_training:
  epochs: 40
  loss: L1
reporting:
  root: /home/vadim/Documents/personal/huggingface/training_dynamics
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
    - image_examples
    - root_acc
